# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy project files
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

# Install dependencies (including dev for build)
RUN npm ci --ignore-scripts

# Build: transpile TypeScript and set executable bit
RUN npx tsc && chmod +x build/index.js

# Default command to start MCP server
CMD ["node", "build/index.js"]
